### ISSUE TITLE
Bad characters display in content treeview

### ISSUE THREAD

**Issue by zdenekkrejci** [RickStrahl/HelpBuilderReleases#100]
In content program panel on the left of main window there is a character encoding which is not corresponding with Codepage of Compiled Help File Language set in project Options (main menu "Tool" -> "Options").
(See attached picture)
![wwhb_wrong_encoding_in_left_panel](https://user-images.githubusercontent.com/16401662/79466004-4daeaa00-7ffc-11ea-86ae-d69dff17a5f2.png)

We use cp 1250, help file language 0x405.
This was OK three years ago.

**Comment by RickStrahl** [comment]
Hmmm... that seems odd since the tree is showing other 'special' characters, just this one.

Do you know if this would account for the difference between the code pages? Does 1252 (the default English/Western Euro charset) has all those other character accent that are working?

The treeview is an ActiveX control so it's not using the Fox code page which is likely why that's not working. The browser and editor use UTF-8 so that should always work. The text control is FoxPro so that respects the codepage.

Intersting that this is the first complaint I've heard about this which would seem to have been a problem from day one in Help Builder.

**Comment by zdenekkrejci** [comment]
Of course these characters are in extended ascii table and chracter "ř" in windows-1250 is chr(248). In windows 1252 it means "ø". And exactly this characters is displayed in treeview.
Interesting that some time ago treeview worked correctly.
Thanks for Your response.

**Comment by RickStrahl** [comment]
Took a look and see what you're describing, but I'm not sure how to fix this.

What Windows language are you in when you start FoxPro as that seems to be the only way I can actually affect the way FoxPro overall behaves with different code pages. I have `CODEPAGE=1250` in my config.fpw, but that doesn't appear to make any difference.

Even with the CP set to 1250 I can't even paste the ř into the textbox nor into the editor (because pasting goes through FoxPro conversion).

**Comment by zdenekkrejci** [comment]
Something has changed in wwHelpBuilder
I have installed the old version (5.0.102) and characters were OK:
![image](https://user-images.githubusercontent.com/16401662/79845510-76002500-83bd-11ea-864d-bbfc20f29da3.png)
Then install the newwest verison and characters are bad:
![image](https://user-images.githubusercontent.com/16401662/79845588-916b3000-83bd-11ea-9c69-a75aab1bbe32.png)
The same project, same configuration. Only version of the program has changed.

Windows and foxpro runs in cp 1250. Codepage for non-unicode app is also 1250.
Thank You.

**Comment by RickStrahl** [comment]
Looking at this again finally but while I can duplicate I'm not sure what causes this or worse what could possibly have changed other than some other version of the control or a change in Windows in how the control handles the active code page. I tried to see if there's some mechanism of setting the code page of the ActiveX control directly but I can't see anything. The code that sets the value is a simple AddNode() call so there's nothing else that can be done there.

I wonder about a couple of things:

* If you edit a node does it properly accept your extended charcacters from the keyboard?
* What happens if you click the Refresh button on the keyboard?
* Does it look to you like another code page? Can you use the command window to set the codepage to another and duplicate those values?

The only thing I can think of is that perhaps applying a custom code page does this. So form starts up in a certain code page, then the code page is changed and the ActiveX control perhaps doesn't see the change.

**Comment by zdenekkrejci** [comment]
After double click is possible to edit node text in place. The text is displayed correctly and keyboard works corectly too.
![pic2](https://user-images.githubusercontent.com/16401662/96335050-bfcc7e00-1075-11eb-9611-4460a99ff0da.jpg)
Before an after edit the text looks wrong.
![pic1](https://user-images.githubusercontent.com/16401662/96335053-c824b900-1075-11eb-95d8-13155a9a4a7d.jpg)
Refresh does nothing. The text is wrong.

Id don´t know, how to use command window in WW HTML help builder.

**Comment by zdenekkrejci** [comment]
Could it be possible that you used in the treeview some font that does not know codepage 1250?

**Comment by RickStrahl** [comment]
The font is standard Tahoma and if you can type into the text edit box and it works, then it should also work for the display - unless there's some code page problem. I'm wondering what the wrong value reflects? Is it what you would see if you display your correct value in CodePage 1252 (which is probably the default)?

Could you paste a string of text that doesn't work here? 

Just not sure what would have changed that this behavior worked in older versions, but not the newer one because the way the tree is built and nodes assigned has changed since the very beginning. 

Command Window: If you VFP 9.0, you can run wwhelp.exe from within the VFP IDE and break to check what the form's active code page is.

**Comment by RickStrahl** [comment]
So I still am unable to try this out because I can't seem to paste something like `ř` into the FoxPro text box.  It works in the editor (which is HTML and thus Unicode), but the edit box is FoxPro. I'm running in CodePage 1250, but it's turning the `ř` into a `r` when I paste it.

Anyway, I checked to see what font is actually used in the tree and it looks like I've switched it some time ago to use `Segoe UI` as all the rest of the main window UI. So that is a change and perhaps that newer MS font no longer has support for non-Unicode codepages. So I've switched this back to Tahoma which may end up fixing this problem so check the next update.

Still would like to be able to see this for myself though which I can't do right now.

**Comment by RickStrahl** [comment]
I pushed up an update for 1.28.5 which has the font change in it. Maybe take a look and see if that works better. I was not able to check it locally even when switching Windows language to Czech (which was quite an adventure to get out of :smile:).

**Comment by zdenekkrejci** [comment]
I installed a new version.
I ran wwhelp.exe in VFP.
The text is still not displayed correctly.
I found a treeview object in the debugger.
Font is a Segoe UI.
Charset = 0.

![pic3](https://user-images.githubusercontent.com/16401662/96361808-41c9af00-1129-11eb-882e-b53a435d7172.jpg)

setting charset to 238 solved the whole problem.
![pic6](https://user-images.githubusercontent.com/16401662/96361926-04b1ec80-112a-11eb-9894-a1775c57d011.jpg)

The text is displayed correctly now.
![pic4](https://user-images.githubusercontent.com/16401662/96361998-7f7b0780-112a-11eb-8684-f643a440b90c.jpg)



Note: cpcurrent()  = 1250.
![pic5](https://user-images.githubusercontent.com/16401662/96361941-27dc9c00-112a-11eb-9d77-fe19104d16ea.jpg)

**Comment by RickStrahl** [comment]
First of all thanks for your help in tracking this down.

A few questions and things I can think of here.

First: what is the value of 238? How would we generically find this value from a code page selection? Right now in HB you can set the codepage to use for the data stored in the database, so we know that you probably want 1250. But how do you go from that to 238?

Have you tried setting the font to Arial or Tahoma in the debugger. Does that help at all because that's likely the only thing that has changed in receent years in the way the tree is rendered. If that doesn't work maybe try MS Sans Serif.

For sure if this worked in the past I never set the code page explicitly, so somehow this worked without having to explicitly set the codepage.

I still can't get a czech value with some of the questionable characters entered into a FoxPro textbox even with the code page set to 1250. I can paste it into the editor, but in the FoxPro textbox the value gets changed (like you describe). 

Also, can you paste a string of text (as text not as a picture so I can easily cut and paste) here please that exhibits the behavior you describe just so there's an easy place to pick up a relevant string for reference.

**Comment by zdenekkrejci** [comment]
I tried to assign different values in the command window. 1250 didn't help. When I started editing the value in the debugger watch window, the value 238 jumped there by itself.
But i solved many years ago in vfp8-9 problem with print report with national characters in some printers. When i checked [x]use font script, the problem was solved. After some reverse ingeneering i´ve found, that this wrote value 238 into field "resoid" in the FRX file.

Tooday after some googling "foxpro font script 238" I´ve found this page:
[http://www.yaldex.com/fox_pro_tutorial/html/53a11bb9-6a3b-4539-a343-ffd75ae45dbe.htm](url)

Here is following table

nFontCharSet | Language script
0 | Western
1 | Default
2 | Symbol
128 | Japanese
161 | Greek
162 | Turkish
163 | Vietnamese
177 | Hebrew
178 | Arabic
186 | Baltic
204 | Cyrillic
238 | Central European

Next interesting link is here
[http://fox.wikis.com/wc.dll?Wiki~FontScriptSupport~VB](url)

Here [https://www.tek-tips.com/viewthread.cfm?qid=1797541](url) is the table:
Codepage of operating system		assigned Character Set
1250 (Central Europe)				EASTEUROPE_CHARSET (238)
1252 (Latin I)					DEFAULT_CHARSET (1)
1251 (Cyrillic)					RUSSIAN_CHARSET (204)
1253 (Greek)					GREEK_CHARSET (161)
1254 (Turkish)					TURKISH_CHARSET (162)
1257 (Baltic)					BALTIC_CHARSET (186)
1258 (Vietnam)					VIETNAMESE_CHARSET (163)
874 (Thai)					THAI_CHARSET (222)
932 (Japanese Shitf-JIS)			SHIFTJIS_CHARSET (128)
936 (Simplified Chinese)			GB2312_CHARSET (134)
950 (Traditional Chinese Big5)			CHINESEBIG5_CHARSET (136)
949 (Korean)					HANGEUL_CHARSET (129))

**Comment by RickStrahl** [comment]
Thank you. Yeah the mapping will work if that's the only way, but that wasn't the case originally, so there should be a way to make this work with charset at default (0).

What about assigning different fonts like Arial or Tahoma? I'd rather not assign the charset explicitly if that can be avoided.

**Comment by zdenekkrejci** [comment]
![pic7](https://user-images.githubusercontent.com/16401662/96412840-0394c400-11eb-11eb-873b-1d3634b7ca9a.jpg)
Change of the fon doesn´t help.
Only the last line of the code solved the problem.

**Comment by RickStrahl** [comment]
Ok so give 5.28.8 a try. I've added code page translation into the startup code so it'll apply the charset based on the active code page.

Let's see if that does it.

**Comment by zdenekkrejci** [comment]
I works now. Thank You.

**Comment by RickStrahl** [comment]
Thank you - I wouldn't have been able to fix it without your help....
